# Assignment 3 Hypothesis testing

In [52]:
#importing the lib
import pandas as pd
import scipy
import numpy as np
from scipy import stats
from scipy.stats import chi2_contingency,chisquare

# Question 1

A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units.
A randomly selected sample of cutlets was collected from both units and measured. 
Analyze the data and draw inferences at 5% significance level.
Please state the assumptions and tests that you carried out to check validity of the assumptions.



In [53]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 5220-A98C

 Directory of C:\Users\abc\OneDrive\Desktop\excelr\Assignments\Hypothesis testing_3

19/08/2022  22:23    <DIR>          .
19/08/2022  22:23    <DIR>          ..
18/08/2022  15:35    <DIR>          .ipynb_checkpoints
19/08/2022  22:23            22,546 Assignment_3_Hypothesistesting_Nihal_Inamdar.ipynb
18/08/2022  16:04                87 BuyerRatio.csv
18/08/2022  16:04            13,423 Costomer+OrderForm.csv
18/08/2022  15:01               525 Cutlets.csv
17/08/2022  19:39             6,493 Hypothesis Test.ipynb
17/08/2022  16:27            61,688 Hypothesis_Testing_Assignment_3.pptx
18/08/2022  15:59             3,487 LabTAT.csv
               7 File(s)        108,249 bytes
               3 Dir(s)  21,799,571,456 bytes free


In [54]:
data=pd.read_csv("Cutlets.csv")

In [55]:
data.head(5)

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [56]:
Treat=pd.Series(data.iloc[:,0])
Treat.head(5)

0    6.8090
1    6.4376
2    6.9157
3    7.3012
4    7.4488
Name: Unit A, dtype: float64

In [57]:
Control=pd.Series(data.iloc[:,1])
Control.head(5)

0    6.7703
1    7.5093
2    6.7300
3    6.7878
4    7.1522
Name: Unit B, dtype: float64

In [58]:
p_value=stats.ttest_ind(Treat,Control)
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.47223947245995)

# Question 2

A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. 
They collected a random sample and recorded TAT for reports of 4 laboratories. 
TAT is defined as sample collected to report dispatch.
   
Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.
 


In [59]:
# null hypothesis= there is a difference in the average Turn Around Time (TAT) of reports of the laboratories.
# alternative hypothesis=there is no difference in the average Turn Around Time (TAT) of reports of the laboratories.
# given alpha= 0.05

In [60]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 5220-A98C

 Directory of C:\Users\abc\OneDrive\Desktop\excelr\Assignments\Hypothesis testing_3

19/08/2022  22:23    <DIR>          .
19/08/2022  22:23    <DIR>          ..
18/08/2022  15:35    <DIR>          .ipynb_checkpoints
19/08/2022  22:23            22,546 Assignment_3_Hypothesistesting_Nihal_Inamdar.ipynb
18/08/2022  16:04                87 BuyerRatio.csv
18/08/2022  16:04            13,423 Costomer+OrderForm.csv
18/08/2022  15:01               525 Cutlets.csv
17/08/2022  19:39             6,493 Hypothesis Test.ipynb
17/08/2022  16:27            61,688 Hypothesis_Testing_Assignment_3.pptx
18/08/2022  15:59             3,487 LabTAT.csv
               7 File(s)        108,249 bytes
               3 Dir(s)  21,799,571,456 bytes free


In [61]:
data_lab=pd.read_csv('LabTAT.csv')
data.head(5)

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [62]:
data_lab.mean()

Laboratory 1    178.361583
Laboratory 2    178.902917
Laboratory 3    199.913250
Laboratory 4    163.682750
dtype: float64

In [63]:
p_value_lab=stats.f_oneway(data_lab.iloc[:,0],data_lab.iloc[:,1],data_lab.iloc[:,2],data_lab.iloc[:,3])
p_value_lab

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [64]:
# Hence p_value_lab < significance level (0.05), thus the null hypothesis is proven false.

# Question 3

Sales of products in four different regions is tabulated for males and females. 
Find if male-female buyer rations are similar across regions.


In [79]:
# null hypothesis= Independence of categorical values
# alternative hypothesis= Dependence of categorical values

In [67]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 5220-A98C

 Directory of C:\Users\abc\OneDrive\Desktop\excelr\Assignments\Hypothesis testing_3

19/08/2022  22:23    <DIR>          .
19/08/2022  22:23    <DIR>          ..
18/08/2022  15:35    <DIR>          .ipynb_checkpoints
19/08/2022  22:23            22,546 Assignment_3_Hypothesistesting_Nihal_Inamdar.ipynb
18/08/2022  16:04                87 BuyerRatio.csv
18/08/2022  16:04            13,423 Costomer+OrderForm.csv
18/08/2022  15:01               525 Cutlets.csv
17/08/2022  19:39             6,493 Hypothesis Test.ipynb
17/08/2022  16:27            61,688 Hypothesis_Testing_Assignment_3.pptx
18/08/2022  15:59             3,487 LabTAT.csv
               7 File(s)        108,249 bytes
               3 Dir(s)  21,799,563,264 bytes free


In [68]:
data_br=pd.read_csv('BuyerRatio.csv')
data_br

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [73]:
data_br1=data_br.drop(['Observed Values'],axis=1)
data_br1

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [76]:
obs=np.array([[50,142,131,70],[435,1523,1356,750]])
obs

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [78]:
chi2_contingency(obs) # o/p is (Chi2 stats value, p_value, df, expected obsvations)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [80]:
# Here, P_value(0.66)>significance value (0.05) thus null hypothesis fall true,
# ie male-female buyer rations are similar across regions and are not related.

# Question 4

TeleCall uses 4 centers around the globe to process customer order forms. 
They audit a certain %  of the customer order forms. 
Any error in order form renders it defective and has to be reworked before processing.  
The manager wants to check whether the defective %  varies by centre. 
Please analyze the data at 5% significance level and help the manager draw appropriate inferences


In [82]:
z=pd.read_csv('Costomer+OrderForm.csv')
z

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [83]:
z.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [86]:
z.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [87]:
z.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [88]:
z.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [90]:
obs1=np.array([[271,267,269,280],[29,33,31,20]])
obs1

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [91]:
chi2_contingency(obs1) # o/p is (Chi2 stats value, p_value, df, expected obsvations)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [92]:
# Here, P_value(0.27)>significance value (0.05) thus null hypothesis fall true,
# thus the defective % does not vary by centre